# Generated by Django 5.1.5 on 2025-03-29 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='break',
            name='study_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.studysession'),
        ),
        migrations.AlterField(
            model_name='studysessionbreakdown',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.categories'),
        ),
        migrations.AlterField(
            model_name='studysessionbreakdown',
            name='study_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.studysession'),
        ),
    ]
