# Generated by Django 5.1.5 on 2025-03-31 01:30

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_break_study_session_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE analytics_aggregate ALTER COLUMN total_duration TYPE integer USING EXTRACT(epoch FROM total_duration)::integer',
            reverse_sql='ALTER TABLE analytics_aggregate ALTER COLUMN total_duration TYPE interval USING make_interval(secs => total_duration)',
        ),
    ]
