# Generated by Django 5.1.5 on 2025-03-31 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_aggregate_total_duration'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                'ALTER TABLE analytics_studysession ALTER COLUMN total_duration TYPE integer USING EXTRACT(epoch FROM total_duration)::integer',
                'ALTER TABLE analytics_studysessionbreakdown ALTER COLUMN duration TYPE integer USING EXTRACT(epoch FROM duration)::integer',
                'ALTER TABLE analytics_break ALTER COLUMN duration TYPE integer USING EXTRACT(epoch FROM duration)::integer',
            ],
            reverse_sql=[
                'ALTER TABLE analytics_studysession ALTER COLUMN total_duration TYPE interval USING make_interval(secs => total_duration)',
                'ALTER TABLE analytics_studysessionbreakdown ALTER COLUMN duration TYPE interval USING make_interval(secs => duration)',
                'ALTER TABLE analytics_break ALTER COLUMN duration TYPE interval USING make_interval(secs => duration)',
            ],
        ),
    ]
