# Generated by Django 5.1.5 on 2025-04-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_aggregate_total_duration_alter_break_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='aggregate',
            name='total_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='break',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='total_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studysessionbreakdown',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
