# Generated by Django 5.1.5 on 2025-05-17 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_studysession_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='productivity_rating',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
