# Generated by Django 5.1.5 on 2025-05-18 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_alter_studysession_productivity_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudySessionBreakdown',
            new_name='CategoryBlock',
        ),
    ]
