# Generated by Django 5.1.5 on 2025-06-06 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_categories_category_type_categories_is_system'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studysession',
            options={'ordering': ['-start_time']},
        ),
    ]
