# Generated by Django 5.1.5 on 2025-06-06 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_alter_studysession_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregate',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aggregate',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
