# Generated by Django 5.1.5 on 2025-06-08 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0014_aggregate_is_final_aggregate_last_updated'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE analytics_studysession DROP COLUMN IF EXISTS timer_type;",
            reverse_sql="-- No reverse operation needed"
        ),
    ]
