# Generated by Django 5.1.5 on 2025-06-21 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0015_auto_20250608_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('total_minutes', models.IntegerField()),
                ('active_weekdays', models.JSONField(default=list)),
                ('carry_over_enabled', models.BooleanField(default=False)),
                ('accumulated_minutes', models.IntegerField(default=0)),
                ('overtime_bank', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('user', 'week_start')},
            },
        ),
        migrations.CreateModel(
            name='DailyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('target_minutes', models.IntegerField()),
                ('accumulated_minutes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('met', 'Met'), ('exceeded', 'Exceeded')], default='pending', max_length=10)),
                ('weekly_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_goals', to='analytics.weeklygoal')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('weekly_goal', 'date')},
            },
        ),
    ]
