# Generated by Django 5.1.5 on 2025-07-11 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0016_weeklygoal_dailygoal'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_duration', models.IntegerField(default=0)),
                ('session_count', models.IntegerField(default=0)),
                ('break_count', models.IntegerField(default=0)),
                ('category_durations', models.JSONField(default=dict)),
                ('timeline_data', models.JSONField(default=list)),
                ('is_final', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'date'], name='analytics_d_user_id_478fdb_idx'), models.Index(fields=['user', 'date', 'is_final'], name='analytics_d_user_id_ee6249_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_start', models.DateField()),
                ('total_duration', models.IntegerField(default=0)),
                ('session_count', models.IntegerField(default=0)),
                ('break_count', models.IntegerField(default=0)),
                ('category_durations', models.JSONField(default=dict)),
                ('daily_breakdown', models.JSONField(default=list)),
                ('heatmap_data', models.JSONField(default=dict)),
                ('is_final', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'month_start'], name='analytics_m_user_id_63e9f3_idx')],
                'unique_together': {('user', 'month_start')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('total_duration', models.IntegerField(default=0)),
                ('session_count', models.IntegerField(default=0)),
                ('break_count', models.IntegerField(default=0)),
                ('category_durations', models.JSONField(default=dict)),
                ('daily_breakdown', models.JSONField(default=dict)),
                ('session_times', models.JSONField(default=list)),
                ('is_final', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'week_start'], name='analytics_w_user_id_e438b6_idx')],
                'unique_together': {('user', 'week_start')},
            },
        ),
    ]
