# Generated by Django 5.1.5 on 2025-07-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0017_create_split_aggregates'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='timezone',
            field=models.CharField(default='UTC', help_text='User timezone (IANA format, e.g., America/New_York)', max_length=50, verbose_name='timezone'),
        ),
    ]
