# Generated by Django 5.1.5 on 2025-07-18 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0018_customuser_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='timezone',
        ),
        migrations.DeleteModel(
            name='Aggregate',
        ),
    ]
