# Generated by Django 5.1.5 on 2025-07-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0019_remove_customuser_timezone_delete_aggregate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='timezone',
            field=models.CharField(default='UTC', help_text='User timezone (e.g., America/New_York, Europe/London)', max_length=50),
        ),
    ]
