# Generated by Django 5.1.5 on 2025-08-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0020_customuser_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyaggregate',
            name='productivity_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyaggregate',
            name='productivity_sessions_count',
            field=models.IntegerField(default=0),
        ),
    ]
