# Generated by Django 5.1.5 on 2025-08-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0021_add_productivity_metrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studysession',
            name='productivity_rating',
        ),
        migrations.AddField(
            model_name='studysession',
            name='focus_rating',
            field=models.CharField(blank=True, help_text="User's self-rated focus level (1-5)", max_length=50, null=True),
        ),
    ]
