# Generated by Django 5.1.5 on 2025-08-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0022_rename_productivity_to_focus'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Whether the user has premium access'),
        ),
    ]
