# Generated by Django 5.1.5 on 2025-08-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0023_add_premium_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyaggregate',
            name='flow_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyaggregate',
            name='flow_score_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlyaggregate',
            name='flow_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlyaggregate',
            name='flow_score_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='flow_components',
            field=models.JSONField(blank=True, help_text='Flow score component breakdown', null=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='flow_score',
            field=models.IntegerField(blank=True, help_text='Flow score (0-1000)', null=True),
        ),
        migrations.AddField(
            model_name='weeklyaggregate',
            name='flow_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyaggregate',
            name='flow_score_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
