# Generated by Django 5.1.5 on 2025-08-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0024_add_flow_score_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_premium',
            field=models.BooleanField(default=True, help_text='Whether the user has premium access (currently defaults to True for testing)'),
        ),
    ]
