# Generated by Django 5.1.5 on 2025-08-31 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0025_default_premium_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyaggregate',
            name='flow_coaching_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlyaggregate',
            name='flow_coaching_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyaggregate',
            name='flow_coaching_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
